### PR TITLE
Fix --skip-pull-requests behavior

### LINKED ISSUE #71: --skip-pull-requests not working
Docs seem to suggest that you can skip pull request and commit straight to master. --skip-pull-requests with branch name as master give the following error 

` Error="a branch named \"refs/heads/master\" already exists"`

### PR DESCRIPTION
**Pull request by zackproser**
## Description

Fixes #71.

Depends on #85, which must be merged first.

## TODOs

Read the [Gruntwork contribution guidelines](https://gruntwork.notion.site/Gruntwork-Coding-Methodology-02fdcd6e4b004e818553684760bf691e).

- [x] Update the docs.
- [x] Run the relevant tests successfully, including pre-commit checks.
- [x] Ensure any 3rd party code adheres with our [license policy](https://www.notion.so/gruntwork/Gruntwork-licenses-and-open-source-usage-policy-f7dece1f780341c7b69c1763f22b1378) or delete this line if its not applicable.
- [x] Include release notes. If this PR is backward incompatible, include a migration guide.

## Release Notes (draft)

Fix `--skip-pull-requests` logic so that pull requests are skipped and the default branch can be used as a target.

### CODE REVIEW

File: repository/repo-operations.go [hunk 1]
```diff
@@ -265,6 +277,13 @@ func updateRepo(config *config.GitXargsConfig, repositoryDir string, worktree *g
 		return pushBranchErr
 	}
 
+	// If the user passed --skip-pull-requests, don't open a pull request
+	if config.SkipPullRequests {
+		wg.Done()
+		p.Increment()
```
Comment (yorinasub17) [inline repository/repo-operations.go:283]: This needs to be updated.

**Review by yorinasub17 — COMMENTED** [review]
Mostly LGTM, just spotted a merge conflict with the concurrency bug fix.

File: repository/repo-operations.go (hunk 1 above)
Comment (zackproser) [reply repository/repo-operations.go]: Thank you! Fixed in 105793bafa223e9ca26bf39d3ed8d6ffd526ce2c

Comment (yorinasub17) [reply repository/repo-operations.go]: Oh I think you needed this if condition to fully skip opening the PR? Otherwise, it will flow through to open the PR, right?

**Review by pete0emerson — APPROVED** [review]
🚢

**Comment by zackproser** [comment]
Thanks for reviews! Going to merge this in now.
