### PR TITLE
Fix stdout/stderr handling

### LINKED ISSUE #24: Improve logging of command STDOUT and STDERR
To assist with debugging why new or complex scripts aren't working as expected, we need better visibility into STDOUT and STDERR for all commands run.

### PR DESCRIPTION
**Pull request by brikis98**
This PR fixes #24. It ensures that `git-xargs` always logs `stdout` / `stderr` from the script, even if the script exits with an error. I've added a test for this too.

Other tweaks in this PR:

1. Refactor `executeCommand` to _only_ run the command. This makes it easier to test this method.
1. Move the `git add` logic that used to be in `executeCommand` into `commitLocalChanges`. This is the more logical home for it.
1. If the work tree reports that the status is clean, don't try to commit anything in `commitLocalChanges`. Previously, the work tree status was only checked in `executeCommand`, and `commitLocalChanges` would try to commit whether or not the status was clean, which was _probably_ a no op, but doesn't seem right.
1. Remove some unused test functions.

### CODE REVIEW

File: cmd/repo-operations.go [hunk 1]
```diff
@@ -104,6 +107,10 @@ func executeCommand(config *GitXargsConfig, repositoryDir string, repo *github.R
 
 	stdoutStdErr, err := cmd.CombinedOutput()
 
+	logger.WithFields(logrus.Fields{
+		"CombinedOutput": string(stdoutStdErr),
+	}).Debug("Received output of command run")
```
Comment (brikis98) [inline cmd/repo-operations.go:112]: This is the real fix. It moves the log statement _before_ the error check to ensure we always get log output.

File: cmd/repo-operations_test.go [hunk 2]
```diff
@@ -26,25 +27,25 @@ func getMockGithubRepo() *github.Repository {
 	return repo
 }
 
-func cloneLocalTestRepo(t *testing.T) (string, *git.Repository) {
```
Comment (brikis98) [inline cmd/repo-operations_test.go:29]: I removed this unused test function

File: cmd/repo-operations_test.go [hunk 3]
```diff
@@ -26,25 +27,25 @@ func getMockGithubRepo() *github.Repository {
...
+	logger := &logrus.Logger{
+		Out:       &buffer,
+		Level:     logrus.TraceLevel,
+		Formatter: new(logrus.TextFormatter),
 	}
 
-	return localPath, localRepo
-}
-
-func cleanupLocalTestRepo(t *testing.T, localPath string) error {
```
Comment (brikis98) [inline cmd/repo-operations_test.go:44]: I removed this unused test function

**Review by zackproser — APPROVED** [review]
LGTM - tyvm
