### PR TITLE
Don't try to open PR if one is already open

### LINKED ISSUE #32: No PR opened, if branch is up to date
Hello,

found something which is probably a bug or at least unexpected behavior.

If, for some reason the changes I made with git-xargs exists already in the branch on github, the tool prints the following errors and does not open a PR.
```
[git-xargs] DEBU[2021-04-27T08:45:41+02:00] Error pushing new branch to remote origin     Error="already up-to-date" Repo=room-management-example
[git-xargs] DEBU[2021-04-27T08:45:41+02:00] Error encountered while processing repo       Error="already up-to-date" Repo name=room-management-example
```

I run into this error, because I run my git-xargs command two times. The first time I run into an error on opening the PR. After fixing this, I run the command a second time and failed on the update. I had to delete the remote branch first.
I think it the tool should not break on an "already up-to-date" message,  because the state of the repository is like it should be, only the way to achived was different.

Think this is an edge case and nothing urgent.

### PR DESCRIPTION
**Pull request by brikis98**
Fixes #32.

Key changes:

1. Check if a PR already exists for a given branch before trying to open up a new one. 
1. Refactor the code a bit into a `updateRepo` method so that if the working tree reports itself as clean, we don't try to commit, push, or open a PR at all.

### CODE REVIEW

**Comment by brikis98** [comment]
Hm, hold on, in manual testing, I'm hitting an issue... Looking into it.

**Comment by brikis98** [comment]
Ah, OK, issue resolved.

File: repository/repo-operations.go [hunk 1]
```diff
@@ -405,3 +453,20 @@ func openPullRequest(config *config.GitXargsConfig, repo *github.Repository, bra
 	config.Stats.TrackPullRequest(repo.GetName(), pr.GetHTMLURL())
 	return nil
 }
+
+// Returns true if a pull request already exists in the given repo for the given branch
+func pullRequestAlreadyExistsForBranch(config *config.GitXargsConfig, repo *github.Repository, branch string, repoDefaultBranch string) (bool, error) {
+	opts := &github.PullRequestListOptions{
+		// Filter pulls by head user or head organization and branch name in the format of user:ref-name or organization:ref-name
+		// https://docs.github.com/en/rest/reference/pulls#list-pull-requests
+		Head: fmt.Sprintf("%s:%s", *repo.Owner.Login, branch),
```
Comment (zackproser) [inline repository/repo-operations.go:462]: NIT: could use the `*repo.GetOwner().Login` method here for consistency.

**Comment by zackproser** [comment]
Great improvement! Mostly LGTM - left a question and a NIT.

File: repository/repo-operations.go (hunk 1 above)
Comment (brikis98) [reply repository/repo-operations.go]: Done: https://github.com/gruntwork-io/git-xargs/pull/34/commits/2a875e8d0f934aa76f9552c3623f8d6084d0a315

File: repository/repo-operations.go [hunk 2]
```diff
@@ -353,6 +379,30 @@ func openPullRequest(config *config.GitXargsConfig, repo *github.Repository, bra
...
+		config.Stats.TrackSingle(stats.PullRequestOpenErr, repo)
+		return errors.WithStackTrace(err)
+	}
+
+	if pullRequestAlreadyExists {
+		logger.WithFields(logrus.Fields{
+			"Repo": repo.GetName(),
+			"Head": branch,
+			"Base": repoDefaultBranch,
+		}).Debug("Pull request already exists for this branch, so skipping opening a pull request!")
```
[the remark this answers is not in the document]
Comment (brikis98) [reply repository/repo-operations.go:402]: Done: https://github.com/gruntwork-io/git-xargs/pull/34/commits/d7d9b0cfcb53d2ee907a3e6f8f2003cee903b41a

**Review by zackproser — APPROVED** [review]
LGTM

**Comment by brikis98** [comment]
Thanks for the review. Merging now.

**Comment by brikis98** [comment]
https://github.com/gruntwork-io/git-xargs/releases/tag/v0.0.6
